### PR TITLE
some fixes of the clair3 pileup C implement

### PR DESCRIPTION
**Pull request by zhengzhenxian**
Hi, Chris @cjw85,

Thanks for rewriting the pileup code in C. I am doing the code review and pls kindly check the PR for some fixes.

### CODE REVIEW

**Comment by cjw85** [comment]
Hi,

We discussed this with @aquaskyline earlier. I'll pull out the feature generation code from medaka and make a fairly standalone python package to make things a bit easier. To summarise some points:

1) I'm happy to restrict the deletion buffer size to a maximum if you are
2) @ftostevin-ont discussed the * -1 for reference bases. Our plan was to do this on the Python side to avoid the C code needing to know about the reference (and also not to intefere with the exisiting code too much). Currently reloading the fasta index and loading the sequence on each call might affect performance.

**Comment by ftostevin-ont** [comment]
If hard-coding the buffer size is an issue, the approach used by medaka is to first loop through the pileup and determine the maximum insertion size, and then to run the loop again to fill the features.

https://github.com/nanoporetech/medaka/blob/2b83074fe3b6a6ec971614bfc6804f543fe1e5f0/src/medaka_counts.c#L351-L357

**Comment by zhengzhenxian** [comment]
> 

Sure, it would be great to simplify the dependencies if possible!

**Comment by zhengzhenxian** [comment]
> If hard-coding the buffer size is an issue, the approach used by medaka is to first loop through the pileup and determine the maximum insertion size, and then to run the loop again to fill the features. Could do the same here with deletion sizes.
> 
> https://github.com/nanoporetech/medaka/blob/2b83074fe3b6a6ec971614bfc6804f543fe1e5f0/src/medaka_counts.c#L351-L357

Thanks@[ftostevin-ont](https://github.com/ftostevin-ont), two-round indel length scan is also a great solution to decide the maximum buffer size.

**Comment by aquaskyline** [comment]
> Hi,
> 
> We discussed this with @aquaskyline earlier. I'll pull out the feature generation code from medaka and make a fairly standalone python package to make things a bit easier. To summarise some points:
> 
> 1. I'm happy to restrict the deletion buffer size to a maximum if you are
> 2. @ftostevin-ont discussed the * -1 for reference bases. Our plan was to do this on the Python side to avoid the C code needing to know about the reference (and also not to intefere with the exisiting code too much). Currently reloading the fasta index and loading the sequence on each call might affect performance.

Re point 1, actually we don't insist on restricting the buffer size. Both double the buffer size when needed or @ftostevin-ont 's suggestion are good. In the previous code that doubles the buffer size, the memset should be using the new_size, and the values in the old buffer should be 

```
dels_f = xrealloc(dels_f, new_size*sizeof(size_t), "dels_f");
memset(dels_f, 0, del_buf_size * sizeof(size_t));
```

**Comment by cjw85** [comment]
@aquaskyline @zhengzhenxian I think you're happy with your code in clair3 now, so I'll close this. I might someday come back to the idea of an independent project for this sort of thing.

**Comment by aquaskyline** [comment]
Ya, thanks, Chris.

**Pull request closed without merging**
