### PR TITLE
Removed name of non-existent script

### PR DESCRIPTION
**Pull request by grzadr**
Script mini-align does not appear to exists in scripts directory.

### CODE REVIEW

**Comment by cjw85** [comment]
@grzadr 
How are you trying to install medaka? If you follow any of the three methods detailed in the README, mini_align will be present.

**Comment by grzadr** [comment]
After cloning repo I ran ```pip3 install --user .``` to avoid creation of virtualenv.

**Comment by grzadr** [comment]
Applying python3 setup.py build results in error 
```error: file '/tmp/pip-gyfsvlfk-build/scripts/mini_align' does not exist```

**Comment by cjw85** [comment]
In order for that to work you will at least need to first run:

    make  libhts.a scripts/mini_align

and ensure you have binaries for `samtools`, `minimap2`, `tabix`, and `bgzip` available.

**Pull request closed without merging**
